spring.application.name=authenticatedbackend

spring.datasource.url=jdbc:postgresql://aws-0-eu-west-2.pooler.supabase.com:5432/postgres?user=postgres.pldjwejtutgbjfchqmny&password=N8rwsLG6bqKvqEDp
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# HikariCP specific properties
spring.datasource.hikari.maximum-pool-size=1
spring.datasource.hikari.pool-name=app1HikariCP



