spring.application.name=EmailVerificationApplication
server.port=8000

email.verification.subject=Email Verification Code
email.verification.body=Hello,\n\nPlease use the following code to verify your email address:\n\nVerification Code: {0} \n\nThank you,\nTeam39
email.verification.sender =team39uon@gmail.com

spring.datasource.url=jdbc:postgresql://aws-0-eu-west-2.pooler.supabase.com:5432/postgres?user=postgres.pldjwejtutgbjfchqmny&password=N8rwsLG6bqKvqEDp
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Connection pool settings
# HikariCP specific properties
spring.datasource.hikari.pool-name=app2HikariCP
spring.datasource.hikari.maximum-pool-size=1


spring.mail.host=smtp.mailgun.org
spring.mail.port=587
spring.mail.username=postmaster@sandbox51fc1037356141969400e6b010c3ba23.mailgun.org
spring.mail.password=2c78aef7d7d16c5dd9a9a177d6e934c1-4b670513-4a292a87
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
